import React from 'react'
import { Global, css } from '@emotion/core'

const GlobalStyle = () => (
  <Global
    styles={css`
      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
      }

      a {
        text-decoration: none;
        color: inherit;
      }

      svg {
        display: block;
      }

      #gatsby-focus-wrapper {
        height: 100%;
      }

      /* This is necessary to allow height 100% for wrappers generated by reach router */
      div[tabindex] {
        height: 100%;
      }
    `}
  />
)

export default GlobalStyle
